artist:
  name: twenty eight
social:
  - name: Facebook
    url: https://www.facebook.com/pg/28capecod
  - name: Instagram
    url: https://www.instagram.com/28_music
  - name: Twitter
    url: https://twitter.com/28music
  - name: Bandcamp
    url: https://twentyeight.bandcamp.com
  - name: Spotify
    url: https://open.spotify.com/artist/4UonzRCI0OOZmgnmE4B8FD
site_language: en
